ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(20) DEFAULT 'loan_officer';
ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name VARCHAR(100);
UPDATE users SET role = 'admin' WHERE role IS NULL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS created_by INTEGER;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS approved_by INTEGER;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS disbursed_by INTEGER;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS disbursed_at TIMESTAMP;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS rejection_reason TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS term_weeks INTEGER;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS interest_amount DECIMAL(12,2);
ALTER TABLE loans ADD COLUMN IF NOT EXISTS total_amount DECIMAL(12,2);
ALTER TABLE loans ADD COLUMN IF NOT EXISTS balance DECIMAL(12,2);
CREATE TABLE IF NOT EXISTS notifications (
  id SERIAL PRIMARY KEY,
  user_id INTEGER,
  loan_id INTEGER,
  type VARCHAR(50) NOT NULL,
  message TEXT NOT NULL,
  read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
