const loanRepository = require('../repositories/loanRepository');
const createLoan            = async (loanData)              => await loanRepository.create(loanData);
const getAllLoans            = async (status)                => await loanRepository.getAll(status);
const getLoanById           = async (id)                    => await loanRepository.getById(id);
const approveLoan           = async (id, approved_by)       => await loanRepository.approve(id, approved_by);
const rejectLoan            = async (id, rejected_by, reason) => await loanRepository.reject(id, rejected_by, reason);
const disburseLoan          = async (id, disbursed_by)      => await loanRepository.disburse(id, disbursed_by);
const updateLoanStatus      = async (id, status)            => await loanRepository.updateStatus(id, status);
const markProcessingFeePaid = async (id, tx)                => await loanRepository.markProcessingFeePaid(id, tx);
const getSchedule           = async (id)                    => await loanRepository.getSchedule(id);
const applyPaymentToSchedule = async (loanId, amount)       => await loanRepository.applyPaymentToSchedule(loanId, amount);
module.exports = { createLoan, getAllLoans, getLoanById, approveLoan, rejectLoan, disburseLoan, updateLoanStatus, markProcessingFeePaid, getSchedule, applyPaymentToSchedule };
